baseline=Baseline again
track=Track me down
EXAM_ADDRESS_1=Address Info
EXAM_DISPLAY_2=Displays the addresses in the Tiny Address Book.
EXAM_NAME_3=Name:
EXAM_STREET_4=Street:
EXAM_APARTME_5=Apartment:
EXAM_CITY_6=City:
EXAM_ZIPCODE_7=Zip Code:
EXAM_NEW_8=Add a new address

ADDRESS_BOOK_TITLE=Example Address Book -- 
